//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportButton.AddDocument {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class AddDocument {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTableCell adddoc;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTableCell addlink;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTable buttonTable;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "14.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(AddDocument target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ScriptBlock @__BuildControl__control2() {
            global::Microsoft.SharePoint.WebControls.ScriptBlock @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptBlock();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
    function CloseCallback() {
             
                     SP.UI.ModalDialog.RefreshPage(SP.UI.DialogResult.OK);
                 }
    
    $(document).ready(function(){
        $(""td[class='ms-addnew']:not([id])"").remove();
    });
       
"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTableCell @__BuildControladddoc() {
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTableCell("td");
            this.adddoc = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "ms-addnew");
            @__ctrl.ID = "adddoc";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "padding-bottom: 3px;");
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Renderadddoc));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__Renderadddoc(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write(@"<span class=""s4-clust"" style=""width: 10px; height: 10px; overflow: hidden; display: inline-block; position: relative;""><img style=""left: 0px !important; top: -32px !important; position: absolute;"" alt="""" src=""/_layouts/15/images/fgimg.png?rev=23""></span>&nbsp;<a class=""ms-addnew"" id=""idHomePageNewDocument"" onclick='NewItem2(event, """);
                                                                                                                                                                                                                                                                                                                                                                                                         @__w.Write(SPUtility.ConcatUrls(SPUtility.ConcatUrls(SPContext.Current.Web.Url,SPUtility.ContextLayoutsFolder), "Upload.aspx") );

            @__w.Write("?List=");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @__w.Write(SPContext.Current.ListId.ToString("B"));

            @__w.Write("&amp;RootFolder=");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   @__w.Write(SPEncode.UrlEncode(SPUtility.ConcatUrls(SPContext.Current.Web.ServerRelativeUrl, SPContext.Current.ListItem.Folder.Url)) );

            @__w.Write("\"); return false;\' href=\"");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          @__w.Write(SPUtility.ConcatUrls(SPUtility.ConcatUrls(SPContext.Current.Web.Url,SPUtility.ContextLayoutsFolder), "Upload.aspx") );

            @__w.Write("?List=");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         @__w.Write(SPContext.Current.ListId.ToString("B"));

            @__w.Write("&amp;RootFolder=");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @__w.Write(SPEncode.UrlEncode(SPUtility.ConcatUrls(SPContext.Current.Web.ServerRelativeUrl, SPContext.Current.ListItem.Folder.Url)) );

            @__w.Write("\" target=\"_self\" data-viewctr=\"4\">Add document</a>");
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTableCell @__BuildControladdlink() {
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTableCell("td");
            this.addlink = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "ms-addnew");
            @__ctrl.ID = "addlink";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "padding-bottom: 3px;");
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Renderaddlink));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__Renderaddlink(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write(@"<span class=""s4-clust"" style=""width: 10px; height: 10px; overflow: hidden; display: inline-block; position: relative;""><img style=""left: 0px !important; top: -32px !important; position: absolute;"" alt="""" src=""/_layouts/15/images/fgimg.png?rev=23""></span>&nbsp;<a class='ms-addnew' onclick=""OpenPopUpPageWithTitle('");
                                                                                                                                                                                                                                                                                                                                                                                     @__w.Write(string.Format("{0}?List={1}&RootFolder={2}&ContentTypeId={3}&Source={4}&IsDlg=1", SPUtility.ConcatUrls(SPUtility.ConcatUrls(SPContext.Current.Web.Url,SPUtility.ContextLayoutsFolder), "NewLink2.aspx"), SPEncode.UrlEncode( SPContext.Current.ListId.ToString("B").ToUpper()),SPEncode.UrlEncode(SPUtility.ConcatUrls(SPContext.Current.Web.ServerRelativeUrl, SPContext.Current.ListItem.Folder.Url)), SPContext.Current.List.ContentTypes["Link Doc"].Id.ToString(),SPEncode.UrlEncode ( HttpContext.Current.Request.Url.PathAndQuery)));

            @__w.Write("\',CloseCallback,600,400,\'Add link doc\'); return false;\" href=\'");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  @__w.Write(string.Format("{0}?List={1}&RootFolder={2}&ContentTypeId={3}&Source={4}&IsDlg=1", SPUtility.ConcatUrls(SPUtility.ConcatUrls(SPContext.Current.Web.Url,SPUtility.ContextLayoutsFolder), "NewLink2.aspx"), SPEncode.UrlEncode( SPContext.Current.ListId.ToString("B").ToUpper()),SPEncode.UrlEncode(SPUtility.ConcatUrls(SPContext.Current.Web.ServerRelativeUrl, SPContext.Current.ListItem.Folder.Url)), SPContext.Current.List.ContentTypes["Link Doc"].Id.ToString(),SPEncode.UrlEncode ( HttpContext.Current.Request.Url.PathAndQuery)));

            @__w.Write("\'>Add link</a>");
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControl__control5(System.Web.UI.HtmlControls.HtmlTableCellCollection @__ctrl) {
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl1;
            @__ctrl1 = this.@__BuildControladddoc();
            @__ctrl.Add(@__ctrl1);
            global::System.Web.UI.HtmlControls.HtmlTableCell @__ctrl2;
            @__ctrl2 = this.@__BuildControladdlink();
            @__ctrl.Add(@__ctrl2);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTableRow @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlTableRow @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTableRow();
            this.@__BuildControl__control5(@__ctrl.Cells);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControl__control3(System.Web.UI.HtmlControls.HtmlTableRowCollection @__ctrl) {
            global::System.Web.UI.HtmlControls.HtmlTableRow @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control4();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTable @__BuildControlbuttonTable() {
            global::System.Web.UI.HtmlControls.HtmlTable @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTable();
            this.buttonTable = @__ctrl;
            @__ctrl.ID = "buttonTable";
            this.@__BuildControl__control3(@__ctrl.Rows);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControlTree(global::ReportButton.AddDocument.AddDocument @__ctrl) {
            global::Microsoft.SharePoint.WebControls.ScriptBlock @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control2();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::System.Web.UI.HtmlControls.HtmlTable @__ctrl2;
            @__ctrl2 = this.@__BuildControlbuttonTable();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
